"""Main script for MXO44 oscilloscope control."""
from instrument import (
    MXO44, ChannelSettings, TriggerSettings, TimebaseSettings,
    WaveformSettings, ArbitraryWaveformSettings, WaveformType,
    DataAcquisitionSettings
)
import os
from datetime import datetime
import numpy as np
import h5py
import random
from pathlib import Path

def create_example_waveform(waveform_type: str = "damped_sine") -> str:
    """Create an example arbitrary waveform CSV file.
    
    Args:
        waveform_type (str): Type of waveform to generate:
            - "damped_sine": Damped sine wave
            - "chirp": Frequency sweep
            - "gaussian_pulse": Gaussian pulse
            
    Returns:
        str: Path to the created CSV file
    """
    # Create data directory if it doesn't exist
    os.makedirs("waveform_data", exist_ok=True)
    
    # Generate waveform data
    sample_rate = 1000000  # 1 MHz
    duration = 0.001      # 1 ms
    t = np.linspace(0, duration, int(sample_rate * duration))
    
    if waveform_type == "damped_sine":
        freq = 10000     # 10 kHz
        decay = 2000     # decay factor
        voltage = np.exp(-decay * t) * np.sin(2 * np.pi * freq * t)
        filename = "damped_sine.csv"
        
    elif waveform_type == "chirp":
        f0, f1 = 1000, 100000  # Frequency sweep from 1kHz to 100kHz
        voltage = np.sin(2 * np.pi * (f0 * t + (f1 - f0) * t**2 / (2 * duration)))
        filename = "chirp.csv"
        
    elif waveform_type == "gaussian_pulse":
        center = duration / 2
        width = duration / 10
        voltage = np.exp(-(t - center)**2 / (2 * width**2))
        filename = "gaussian_pulse.csv"
        
    else:
        raise ValueError(f"Unknown waveform type: {waveform_type}")
    
    # Scale voltage to be within ±1V
    voltage = voltage / np.max(np.abs(voltage))
    
    # Save to CSV file
    csv_file = f"waveform_data/{filename}"
    with open(csv_file, 'w') as f:
        f.write(f"Rate = {sample_rate}  // Sample rate for the ARB file\n")
        for v in voltage:
            f.write(f"{v}\n")
            
    return csv_file

def use_mnist_waveform(scope, index=None, digit=None):
    """Load a MNIST digit waveform and configure it on the oscilloscope.
    
    This function loads a digit waveform generated by generate_mnist_waveforms.py
    and configures it on the MXO44's arbitrary waveform generator.
    
    Args:
        scope: MXO44 instrument instance
        index: Specific index of the waveform to use (0-99 if using default 100 samples)
        digit: Specific digit to load (0-9). If provided, a random example of this digit will be chosen.
        
    Returns:
        Tuple of (digit_label, csv_file_path) used
    """
    mnist_dir = Path("waveform_data/mnist")
    
    # Handle cases where the waveforms haven't been generated yet
    if not mnist_dir.exists():
        print("MNIST waveforms not found. Please run generate_mnist_waveforms.py first.")
        return None, None
    
    # If index is provided, try to find that specific waveform
    if index is not None:
        csv_files = list(mnist_dir.glob(f"mnist_digit_*_{index}.csv"))
        if csv_files:
            csv_file = csv_files[0]
            digit_label = int(csv_file.stem.split('_')[2])
        else:
            print(f"No waveform found with index {index}, falling back to random selection")
            index = None
    
    # If digit is provided but not index, find a random example of that digit
    if digit is not None and index is None:
        csv_files = list(mnist_dir.glob(f"mnist_digit_{digit}_*.csv"))
        if csv_files:
            csv_file = random.choice(csv_files)
            digit_label = digit
        else:
            print(f"No waveforms found for digit {digit}, falling back to random selection")
            digit = None
    
    # If neither index nor digit are provided or found, pick a random waveform
    if index is None and digit is None:
        csv_files = list(mnist_dir.glob("mnist_digit_*.csv"))
        if not csv_files:
            print("No MNIST waveforms found. Please run generate_mnist_waveforms.py first.")
            return None, None
        
        csv_file = random.choice(csv_files)
        # Extract digit from filename (format: mnist_digit_<digit>_<index>.csv)
        digit_label = int(csv_file.stem.split('_')[2])
    
    print(f"Using MNIST digit: {digit_label}, file: {csv_file}")
    
    # Configure arbitrary waveform on the oscilloscope
    arb_settings = ArbitraryWaveformSettings(
        csv_file=str(csv_file),
        sample_rate=1e6,  # 1 MHz (adjust based on your waveform parameters)
        run_mode="REPetitive"
    )
    scope.configure_arbitrary_waveform(arb_settings)
    
    return digit_label, csv_file

def main():
    """Test MXO44 oscilloscope control functionality."""
    # Create instrument instance
    scope = MXO44()
    
    try:
        # Connect to instrument
        if not scope.connect():
            print("Failed to connect to instrument")
            return
            
        # Get instrument identification
        print(f"Instrument: {scope.instrument.idn_string}")
        print(f"Options: {scope.instrument.instrument_options}")
        
        # Reset instrument to default state
        scope.write("*RST")
        
        # Configure Channel 1 using dataclass
        channel_settings = ChannelSettings(
            state="ON",
            coupling="DC",
            range=1.0,  # 1V/div
            offset=0.0
        )
        scope.configure_channel(1, channel_settings)
        
        # Configure trigger using dataclass
        trigger_settings = TriggerSettings(
            mode="NORMAL",
            source="CH1",
            level=0.0,
            slope="POS"
        )
        scope.configure_trigger(trigger_settings)
        
        # Configure timebase using dataclass
        timebase_settings = TimebaseSettings(
            scale=0.0001  # 100µs/div
        )
        scope.configure_timebase(timebase_settings)
        
        # Choose between standard waveform, arbitrary waveform, or MNIST waveform
        waveform_type = "mnist"  # "standard", "arbitrary", or "mnist"
        
        if waveform_type == "mnist":
            # Use MNIST digit waveform
            print("\nUsing MNIST digit waveform...")
            digit, csv_file = use_mnist_waveform(scope, digit=None)  # Try with digit=5 for a specific digit
            if digit is None:
                print("Fallback to standard arbitrary waveform")
                waveform_type = "arbitrary"
            else:
                print(f"Configured MNIST digit {digit} waveform")
        
        if waveform_type == "arbitrary":
            # Create and configure arbitrary waveform
            print("\nCreating arbitrary waveform...")
            csv_file = create_example_waveform("chirp")  # Try different waveform types
            print(f"Created waveform file: {csv_file}")
            
            print("\nConfiguring arbitrary waveform generator...")
            arb_settings = ArbitraryWaveformSettings(
                csv_file=csv_file,
                sample_rate=2e6,  # Optional: override sample rate
                run_mode="REPetitive"
            )
            scope.configure_arbitrary_waveform(arb_settings)
            
        elif waveform_type == "standard":
            # Configure standard waveform
            print("\nConfiguring standard waveform generator...")
            wgen_settings = WaveformSettings(
                function=WaveformType.SQUARE,
                frequency=1000,  # 1kHz
                amplitude=1.0,   # 1Vpp
                offset=0.0,      # 0V DC offset
                duty_cycle=50,   # 50% duty cycle
                output="ON"
            )
            scope.configure_waveform_generator(wgen_settings)
        
        # Create data directory if it doesn't exist
        data_dir = "waveform_data"
        os.makedirs(data_dir, exist_ok=True)
        
        # Generate filename with timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        csv_filename = os.path.join(data_dir, f"captured_waveform_{timestamp}.csv")
        plot_filename = os.path.join(data_dir, f"captured_waveform_{timestamp}.png")
        
        # Customize plot settings (optional)
        scope.plot_settings.figure_size = (15, 8)  # Larger plot
        scope.plot_settings.dpi = 300  # Higher resolution
        scope.plot_settings.show_grid = True
        scope.plot_settings.show_info = True
        
        # Save waveform data to CSV
        print("\nSaving captured waveform data...")
        scope.save_waveform_data(1, csv_filename)
        print(f"Waveform data saved to {csv_filename}")
        
        # Plot waveform
        print("\nPlotting captured waveform...")
        scope.plot_waveform(1, plot_filename)
        
    except Exception as e:
        print(f"Error: {str(e)}")
    finally:
        # Disconnect from instrument
        scope.disconnect()

if __name__ == "__main__":
    main() 